print("\n\t\t\tFile Handling")
print("\t\t\t-------------")
f=open("D:\\demo\\first.txt","w")
p=input("\nEnter a paragraph:")
f.write(p)
f.close( )
fr=open("D:\\demo\\first.txt","r")
print("\n\nContent in file:")
print("------------------")
print(fr.readlines( ))
